/**
 * Auto-generated TypeScript types for discovered APIs
 * Generated by APX
 * Package: discovered-api
 * Generated at: 2025-11-26T23:52:49.460Z
 */

export type PostsGETResponse = PostsGETResponseItem[];

export interface PostsGETMeta {
  page?: number;
  totalPages?: number;
  total?: number;
  hasNext?: boolean;
}

// Utility types
export type ApiResponse<T> = T;
export type ApiError = {
  message: string;
  code?: string;
};
