# Auto-generated API Client SDK
# Generated by APX

import requests
from typing import Dict, Any, Optional

class ApiClient:
    def __init__(self, base_url: str = 'https://jsonplaceholder.typicode.com', headers: Optional[Dict[str, str]] = None):
        self.base_url = base_url
        self.headers = headers or {}

    def getPosts(self, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """GET /posts"""
        url = f"{self.base_url}/posts"
        
        kwargs = {'headers': self.headers}
        if params:
            kwargs['params'] = params
        
        response = requests.get(url, **kwargs)
        response.raise_for_status()
        return response.json()

