// Auto-generated API Client SDK
// Generated by Smart API Finder & Documenter

package apiclientjsonplaceholdertypicodecom

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
)

type ApiClient struct {
	BaseURL string
	Headers map[string]string
	Client  *http.Client
}

func NewApiClient(baseURL string, headers map[string]string) *ApiClient {
	if baseURL == "" {
		baseURL = "https://jsonplaceholder.typicode.com"
	}
	return &ApiClient{
		BaseURL: baseURL,
		Headers: headers,
		Client:  &http.Client{},
	}
}

func (c *ApiClient) Getposts(params map[string]string) (map[string]interface{}, error) {
	urlStr := fmt.Sprintf("%s%s", c.BaseURL, "/posts")
	
	urlObj, err := url.Parse(urlStr)
	if err != nil {
		return nil, err
	}
	
	if params != nil {
		q := urlObj.Query()
		for k, v := range params {
			q.Set(k, v)
		}
		urlObj.RawQuery = q.Encode()
	}
	
	var req *http.Request
	req, err = http.NewRequest("GET", urlObj.String(), nil)
	if err != nil {
		return nil, err
	}
	if err != nil {
		return nil, err
	}
	
	for k, v := range c.Headers {
		req.Header.Set(k, v)
	}
	
	resp, err := c.Client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	
	var result map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, err
	}
	
	return result, nil
}

